### ISSUE TITLE
Retrieve systemNumber for Seasonal Forecast files

### ISSUE THREAD

**Issue by EddyCMWF** [ecmwf/cfgrib#98] opened 2019-07-18 14:18 UTC
Hi,

Is it possible to include the systemNumber value in the metadata fields retrieved by cfgrib? This is a standard metadata field in the seasonal forecast data and is recognised by eccodes.

The problem is that that when people convert to netCDF the traceability to the forecast configuration is lost if the systemNumber is not retained somewhere.

Many thanks,
Eddy

**Comment by alexamici** [comment] 2019-07-22 21:36
This issue is really a duplicate of #89, but I must admit that the way it is formulated made my think to the problem just a bit differently and now I'm working to programmatically request to add arbitrary `keys` to the attributes at `open_dataaset` time.

You can follow the development in branch `stable/0.9.7.x`.

**Comment by alexamici** [comment] 2019-07-22 21:58
@EddyCMWF you can now add the `read_keys` argument to `backend_kwargs` with a list of the keys you want to add. Note that all keys MUST have the same value for all messages in a variable:

```
>>> ds = xr.open_dataset('seas5.grib', engine='cfgrib', backend_kwargs={'read_keys':['systemNumber']})
>>> ds.mx2t24
<xarray.DataArray 'mx2t24' (time: 2, step: 3, latitude: 61, longitude: 120)>
dask.array<shape=(2, 3, 61, 120), dtype=float32, chunksize=(2, 3, 61, 120)>
Coordinates:
    number      int64 ...
  * time        (time) datetime64[ns] 2018-04-01 2018-05-01
  * step        (step) timedelta64[ns] 30 days 31 days 61 days
    surface     int64 ...
  * latitude    (latitude) float64 90.0 87.0 84.0 81.0 ... -84.0 -87.0 -90.0
  * longitude   (longitude) float64 0.0 3.0 6.0 9.0 ... 348.0 351.0 354.0 357.0
    valid_time  (time, step) datetime64[ns] dask.array<shape=(2, 3), chunksize=(2, 3)>
Attributes:
    GRIB_paramId:                             51
    GRIB_shortName:                           mx2t24
    ...
    GRIB_systemNumber:                        5
    long_name:                                Maximum temperature at 2 metres...
    units:                                    K
```

**Closed** 2019-07-23 06:25 UTC
Labels: enhancement
