### ISSUE TITLE
valid_time is computed incorrectly

### ISSUE THREAD

**Issue by iainrussell** [ecmwf/cfgrib#11] opened 2018-08-02 10:45 UTC
It seems to add the step, which is in hours, as if it is actually in seconds.

For example, try with this GRIB file in the sample-data folder:
multi_param_on_multi_dims.grib

time is 2018-04-04T12:00:00
steps are 0, 12, 24, 36 hours
valid_time is 
array(['2018-04-04T12:00:00.000000000', '2018-04-04T12:00:12.000000000',
       '2018-04-04T12:00:24.000000000', '2018-04-04T12:00:36.000000000'],

**Comment by iainrussell** [comment] 2018-08-06 07:24
This is an important attribute of any field, so it needs to be easy to make a coordinate out of it - people would usually want to match fields on valid_time, so we should either have a function for them to call, or have a clear example of what they should do!

**Comment by jjday** [comment] 2018-08-07 13:18
Hi, just to add that having inbuilt functionality to easily index the data according to the valid_time is absolutely crucial. Otherwise, the standard arithmetic behavior in xarray, which pairs the data based on the time coordinate will not behave in a way that is intuitive/useful for a meteorologist, and much of the useful functionality associated with xarray will be lost.

**Comment by aurghs** [comment] 2018-08-07 13:57
@iainrussell,  @alexamici , you are right, the problem is a time unit conversion. 
For now I have fixed the bug in `dataset.py` and it will be available with the next release.
I think the conversion in `dataset.py` shouldn't be a big problem:  we only need to know the units of the inputs of `build_valid_time` which are currently in seconds and hours, since they are always computed by `cfmessage.from_grib_step`, `cfmessage.from_grib_date_time`. Clearly the functions should be synchronized.

**Comment by alexamici** [comment] 2018-08-13 08:36
Closed in release 0.8.4.3.

**Closed by alexamici** 2018-08-13 08:36 UTC
Labels: bug
