### ISSUE TITLE
import error for latest version of cfgrib (0.9.9.0) on linux

### ISSUE THREAD

**Issue by bidhya** [ecmwf/cfgrib#226] opened 2021-04-11 18:28 UTC
The lastest release of cfgrib cannot be imported on linux system. I think the same issue is creating error for xarray (https://github.com/pydata/xarray/issues/5138 ).

On windows system, however, everything seems to work fine.

`import cfgrib
`
ImportError                               Traceback (most recent call last)
<ipython-input-3-30e689ead031> in <module>
----> 1 import cfgrib

~/miniconda3/lib/python3.8/site-packages/cfgrib/__init__.py in <module>
     17 
     18 # cfgrib core API depends on the ECMWF ecCodes C-library only
---> 19 from .cfmessage import CfMessage
     20 from .dataset import Dataset, DatasetBuildError, open_file, open_fileindex
     21 from .messages import FileStream, Message

~/miniconda3/lib/python3.8/site-packages/cfgrib/cfmessage.py in <module>
     27 import numpy as np  # type: ignore
     28 
---> 29 from . import messages
     30 
     31 LOG = logging.getLogger(__name__)

~/miniconda3/lib/python3.8/site-packages/cfgrib/messages.py in <module>
     26 
     27 import attr
---> 28 import eccodes  # type: ignore
     29 import numpy as np  # type: ignore
     30 

~/miniconda3/lib/python3.8/site-packages/eccodes/__init__.py in <module>
     13 import sys
     14 
---> 15 from .eccodes import *
     16 from .eccodes import __version__
     17 from .eccodes import bindings_version

~/miniconda3/lib/python3.8/site-packages/eccodes/eccodes.py in <module>
     10 #
     11 #
---> 12 from gribapi import __version__
     13 from gribapi import bindings_version
     14 

~/miniconda3/lib/python3.8/site-packages/gribapi/__init__.py in <module>
     11 #
     12 
---> 13 from .gribapi import *  # noqa
     14 from .gribapi import __version__
     15 from .gribapi import bindings_version

~/miniconda3/lib/python3.8/site-packages/gribapi/gribapi.py in <module>
     30 import numpy as np
     31 
---> 32 from .bindings import ENC, ffi, lib
     33 from .bindings import __version__ as bindings_version  # noqa
     34 from . import errors

~/miniconda3/lib/python3.8/site-packages/gribapi/bindings.py in <module>
     27 
     28 try:
---> 29     from ._bindings import ffi, lib
     30 except ModuleNotFoundError:
     31     ffi = cffi.FFI()

ImportError: /home/miniconda3/lib/python3.8/site-packages/gribapi/_bindings.cpython-38-x86_64-linux-gnu.so: undefined symbol: codes_bufr_key_is_header

**Comment by alexamici** [comment] 2021-04-11 18:58
@bidhya can you report more info on your install?

For example, it looks like you are using *conda*, if this is the case can you report the result of `conda env export`?

Or any other interesting detail of your setup.

**Comment by alexamici** [comment] 2021-04-11 19:08
I cannot reproduce on a clean environment:
```
$ docker run -ti continuumio/miniconda3
# conda install -c conda-forge cfgrib
...
# cfgrib selfcheck
Found: ecCodes v2.21.0.
Your system is ready.
```
I suspect it is a misalignment between the *conda* packages of `eccodes` and `python-eccodes`.

**Comment by alexamici** [comment] 2021-04-11 21:18
Ok, this is a duplicate of https://github.com/conda-forge/python-eccodes-feedstock/issues/69 for which a I submitted a tentative fix: https://github.com/conda-forge/python-eccodes-feedstock/pull/71

Anyway @bidhya to solve the problem now you may try: `conda install -c conda-forge "eccodes>=2.20"`

**Comment by bidhya** [comment] 2021-04-12 01:50
Thanks @alexamici . Updating to eccodes>=2.20 seems to resolve this issue.

**Comment by alexamici** [comment] 2021-04-13 17:38
The Pr has been accepted.

**Closed by alexamici** 2021-04-13 17:38 UTC
